server:
  port: 8761
---
spring:
  profiles: develop
spring:
  cloud:
    discovery:
      enabled: true
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
---
spring:
  profiles: docker
spring:
  cloud:
    config:
      uri: http://configserver:8888
    discovery:
      enabled: true
eureka:
  instance:
    hostname: discovery
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://discovery:${server.port}/eureka/