server:
  port: 9000
spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false
  cloud:
    config:
      uri: http://localhost:8888
  jpa:
   hibernate:
    ddl-auto: create-drop
    naming:
      strategy: org.hibernate.cfg.ImprovedNamingStrategy
   database: HSQL
  datasource:
   url: jdbc:hsqldb:hsql://localhost/expert
   username: root
   password: root
   driver-class-name: org.hsqldb.jdbc.JDBCDriver
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

ribbon:
  eureka:
    enabled: true

